print ("Bem vindo LopesApp/by elias")
print ("-----------")
print ("escolha seu pacote de viagem")
print ("-----------")
viagem = input ("gold | silver?")
praias_visitadas = input ("praias visitadas?")
dias_hospedagem = input ("quantos dias de hospedagem?")
destino  = input ("qual a cidade do destino")

print ("seu pacote é:", viagem)
print ("suas praias visitadas são:", praias_visitadas)
print ("diarias reservadas são:", dias_hospedagem)
print ("seu destino é:", destino)
print ("------------")
print ("volte sempre")